# Generated by Django 5.0.1 on 2024-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RdbmsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
