# Generated by Django 5.0.1 on 2024-01-08 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdbms', '0002_rdbmsmanager_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdbmsmanager',
            name='host',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
